- platform: facebook
  url: "#"
  icon: "fab fa-facebook-f"

- platform: twitter
  url: "#"
  icon: "fab fa-twitter"

- platform: linkedin
  url: "#"
  icon: "fab fa-linkedin-in"

- platform: github
  url: "#"
  icon: "fab fa-github"

- platform: dribbble
  url: "#"
  icon: "fab fa-dribbble"
